import Taskbar from '@/components/Taskbar';
import StoreProvider from '@/state/StoreProvider';
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <StoreProvider>
            <html lang="en">
                <body className='bg-body dark:bg-body-dark'>
                    <Taskbar />
                    {children}
                </body>
            </html>
        </StoreProvider>
    );
}
