export const SUPPORTED_CURRENCIES = [
    {
        countryName: 'Brazil',
        countryCode: 'BR',
        currency: 'Brazilian Real',
        currencyCode: 'BRL',
        currencySymbol: 'R$',
        alignment: 'left',
    },
    {
        countryName: 'India',
        countryCode: 'IN',
        currency: 'Indian Rupee',
        currencyCode: 'INR',
        currencySymbol: '₹',
        alignment: 'left',
    },
    {
        countryName: 'Indonesia',
        countryCode: 'ID',
        currency: 'Indonesian Rupiah',
        currencyCode: 'IDR',
        currencySymbol: 'Rp',
        alignment: 'left',
    },
    {
        countryName: 'Malaysia',
        countryCode: 'MY',
        currency: 'Malaysian Ringgit',
        currencyCode: 'MYR',
        currencySymbol: 'RM',
        alignment: 'left',
    },
    {
        countryName: 'Philippines',
        countryCode: 'PH',
        currency: 'Philippine Peso',
        currencyCode: 'PHP',
        currencySymbol: '₱',
        alignment: 'left',
    },
    {
        countryName: 'United States',
        countryCode: 'US',
        currency: 'United States Dollar',
        currencyCode: 'USD',
        currencySymbol: '$',
        alignment: 'left',
    },
]