import Taskbar from '@/components/taskbar/Taskbar';
import Sidebar from '@/components/sidebar/Sidebar';
import StoreProvider from '@/state/StoreProvider';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import "../globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
    // Await params to avoid the Next.js sync dynamic API error
    const { locale } = await params;

    // Ensure the incoming `locale` is valid
    if (!locale || !routing.locales.includes(locale)) {
        notFound();
    }

    // Fetch messages for the locale
    const messages = await getMessages({ locale });

    return (
        <StoreProvider>
            <html lang={locale}>
                <body className='bg-body dark:bg-body-dark'>
                    <NextIntlClientProvider messages={messages}>
                        <Taskbar />
                        <Sidebar />
                        {children}
                    </NextIntlClientProvider>
                </body>
            </html>
        </StoreProvider>
    );
}
